### PR TITLE
+ LZW compression and use for TIFF images that are LZW-compressed

### PR DESCRIPTION
**Pull request by carygravel**
This is where I am at the moment. The LZW compression/decompression code round-trips for everything I have seen so far. However, it is SLOW.

Some of your collection of TIFFs still do not display properly. I currently suspect this is not due to the LZW compression, but rather because of missing image parameters in the PDF. Can you help me fix this?

Once we have the display bugs fixed, I'll look at addressing the performance problems.

### CODE REVIEW

**Comment by PhilterPaper** [comment]
All my TIFFs were collected "in the wild". I did not create any of them. I think it would be necessary to accommodate missing image parameters, rather than fixing the images (if that's what you are asking).

It doesn't sound good that you have to decompress/recompress everything. It doesn't sound like it's any improvement over the original LZW-to-Flate cycle, except that perhaps some edge/corner cases are fixed?

Anyway, a "heads up" that I'm going to revert the TIFF code so that I can get 3.022 out the door, and we won't feel rushed to get the LZW matter dealt with, as it's apparently a pretty big deal.

**Comment by carygravel** [comment]
> All my TIFFs were collected "in the wild". I did not create any of them. I think it would be necessary to accommodate missing image parameters, rather than fixing the images (if that's what you are asking).

Absolutely. I was asking you to help me find the correct image parameters, not change the TIFFs.

**Comment by PhilterPaper** [comment]
Well, you are _at least_ as skilled in TIFF itself, and as familiar with TIFF-handling in PDF::Builder, as I am! As far as looking inside a TIFF file for possibly missing or corrupt tags, all I have is something I got off the web, **AsTiffTagViewer**, which dumps all the tags. If you can't find it, or can't run it on Linux, I could dump the tags for the offending TIFF files and send them to you. Let me know.

When working on the TIFF code, I've seen some things that look a little _odd_ to me (mostly missing tags), but I'm not expert enough on TIFF to say that could be a reason that some library fails.

**Comment by carygravel** [comment]
> Well, you are _at least_ as skilled in TIFF itself, and as familiar with TIFF-handling in PDF::Builder, as I am!

I meant manipulating the PDF options.

Now that this has diverged from master, I'll create a new branch and delete this.

**Pull request closed without merging**
