### PR TITLE
don't skip tests if convert and tiffcp are present

### PR DESCRIPTION
**Pull request by carygravel**

### CODE REVIEW

**Comment by PhilterPaper** [comment]
I think I see a problem here. Windows does not have /dev/null, so `>/dev/null` will likely blow up in some manner. For Windows, I think the equivalent may be `>NULL:`. You may have to do an if-else based on `$^O eq 'MSWin32'`. I don't know about Macs (I think it's `'MacOS'`), but I can't test it. Is there an OS-independent way of testing if **convert** and **tiffcp** exist? Are they Perl modules, or something in the OS? There _is_ an executable on my system called 'convert', but I don't know if it's the one you're looking for. I also see 'mv' used, which isn't on Windows.

I don't know if the message for test 10 about _Files created with tiffcp -c g3 previously produced the message 'Chunked CCITT G4 TIFF not supported'_ is still valid, at least when you're using Graphics::TIFF. All this stuff is quite old and probably wasn't fully updated when I added support for Graphics::TIFF. I think the last 3 tests (9, 10, 11) should be gone over carefully to see what's going on today, with or without Graphics::TIFF, and OS-independent. It should be possible to detect if Graphics::TIFF is installed, so perhaps the tests could branch on that.

Is it really necessary in the first place to run tiffcp and convert? Are we testing them in some way? If not, could I just supply an already-built TIFF file for the tests? If it is necessary to build the TIFF files here, I'm not adverse to just running these tests on Linux and maybe Mac, but I'll have to draft someone to test on those OS's -- at **each** release, as I really don't want to put out a t-test that I can't test myself.

**Comment by PhilterPaper** [comment]
OK, it looks like `convert` comes from **ImageMagick** and `tiffcp` is a standard (?) Linux utility. The first requires an installation on any platform, and the second requires  an installation on Windows. What happens in tests 9-11:

9. A 568x1000 test.tif file is created with `convert`, with certain characteristics. PDF::Builder is used to print that TIFF file to a PDF "test.pdf". Finally, both test.tif and test.pdf are converted via `convert` to some text (?) format and compared, with the expected result 'alpha'. I presume that the `tiff2pdf` mentioned in the skip is some other utility, which is not involved here. This test you did not attempt to enable.
10. A 568x1000 test.tif file is created with `convert`, with certain characteristics. `tiffcp` is used to compress it (G3) to tmp.tif, which is then renamed (mv) to test.tif. PDF::Builder is used to print that TIFF file to a PDF "test.pdf". Finally, both test.tif and test.pdf are converted via `convert` to some text (?) format and compared, with the expected result 'G3 (not converted to flate)'. 
11. A 568x1000 test.tif file is created with `convert`, with certain characteristics. `tiffcp` is used to compress it (LZW) to tmp.tif, which is then renamed (mv) to test.tif. PDF::Builder is used to print that TIFF file to a PDF "test.pdf". Finally, both test.tif and test.pdf are converted via `convert` to some text (?) format and compared, with the expected result 'lzw (converted to flate)'. 

I don't have either utility, so I can't tell exactly what's going on. If someone could supply me with test9.tif, test10.tif, and test11.tif; ready to be read by PDF::Builder (and quite a bit smaller than 568x1000), that would solve part of the problem. Then the question is, what are we getting from `convert` on the back of the test -- what is it looking for? From the 'expected' strings, is looks like it might be looking for error messages -- are they in the PDF or are they from `convert`? I'm trying to avoid having to run `convert` and `tiffcp` in the first place, so those utilities don't have to be prereq'd. Is it possible to directly find some error message in the PDF, or during its creation? If someone with these utilities could figure out what's being tested, we could hopefully get rid of `convert` and `tiffcp`.

**Comment by carygravel** [comment]
Part of this is a fundamental difference of way of working between Linux and Windows. As you say, `convert` is part of imagemagick. `tiffcp` is part of `libtiff`. Both are readily available on Linux, so creating them on the fly is no problem.

Tests 10 and 11 are simply there to ensure that PDF::Builder can deal with TIFFs encoded with G3/4 or LZW.

Without libtiff, Graphics::TIFF won't work, so neither test should pass, as the pure Perl TIFF loader in PDF::Builder can't handle them. For reference, here is a zip with the two files.

In their current form, the tests cannot run without convert, as they use convert to compare (pixel by pixel) the PDFs from PDF::Builder with the test TIFFs.

[tiff.zip](https://github.com/PhilterPaper/Perl-PDF-Builder/files/5402925/tiff.zip)

**Comment by carygravel** [comment]
Done

**Comment by PhilterPaper** [comment]
Thank you for the two sample .tif files. At this point, since `convert` is still needed for the back-end of the tests, I'm not sure there's much point in using them. Would not needing `tiffcp` be sufficient justification for using them?

Do you know the status of Test 9 (alpha)? Should it remain skipped, or can that test be enabled (Linux only)? It looks like the three tests will work only on Linux, which concerns me, as I have no way of testing them (nor on Mac). Would all three also require libtiff (Graphics::TIFF)? If so, a check should be added to skip if running the pure Perl TIFF library (`$pdf->LA_GT()` returns _true_ if libtiff available).

If I use your supplied .tif files, the only restriction (to Linux) is then that we need to do a pixel-by-pixel comparison of the PDF and the .tif file. I'm not sure how well the t-test system will work with binary data like a pixel stream -- I would guess that's why someone went ahead and used `convert` in the first place. Any thoughts on whether a Quick & Dirty equivalent could be whipped up using Perl and PDF::Builder with Graphics::TIFF? That might lead to questioning of the results, if there is a bug in the libraries! As the files will likely be in a compressed form, it's sounds unlikely that a simple comparison of the byte streams would work.

I'm a bit concerned about using the `English` module -- is this in the core at least as far back as 5.20, and preferably earlier?  And there are almost 2000 tickets open against it!

**Comment by PhilterPaper** [comment]
Regarding checking the images themselves, it would take someone checking a PDF by eye and then if it's OK as the reference, dumping the graphics data in a format that the test harness could understand. That would be comparing a PDF to data dumped from a known good PDF, rather than comparing to the TIFF file. An alternative might be to compare the entire PDF file to a known-good PDF reference file shipped with the package. I'm assuming that could be done by the test harness. I don't know what is going to vary between the two -- I don't think there are any timestamps, but there _is_ a PDF::Builder version number somewhere. Whether the objects can be guaranteed to come out in the same order, IDK. Any incidental changes in the PDF from one release to the next would be a difference, too.

Perhaps these three tests should be moved out of the t-tests and put in the examples (using canned input .tif files). That way, they could be examined by eye, but that's not really what the examples directory is for... At least, non-Linux users could manually test if they suspect something is going wrong with the TIFF support?

**Comment by PhilterPaper** [comment]
I'm going ahead and merging this, but will update the skip messages and maybe do some minor tweaks. Thanks for the work on this!

**Comment by PhilterPaper** [comment]
There doesn't seem to be a way to email you through GitHub, so I'll have to communicate this way. I have merged your code (again, thank you). I updated the skip messages, and also enabled test 9 (alpha). I never heard back from you whether you had tried running it, or you had and it failed. Anyway, here is my revised tiff.t. Could you please run it 3 times for me (`perl tiff.t`)? 1) with Graphics::TIFF disabled (e.g., rename TIFF/ to TIFFx/), 2) with Graphics::TIFF disabled and 'convert' hidden (e.g., renamed), 3) just 'convert' hidden. I need to know if tests 9, 10, and 11 require Graphics::TIFF (libtiff). For case 1, they should fail (blow up in some manner) if they require libtiff. For cases 2 and 3, all three should be skipped (no 'convert'). For those that require libtiff, please try uncommenting the 'skip' for Graphics::TIFF (tests 10 and 11). It might have to be added to test 9. Repeat the 3 cases -- if 'convert' is missing, all three should be skipped, if libtiff is missing, tests 10 and 11 should be skipped (and 9, if you added the skip to that test). I've already tested that it skips all three on Windows. Thanks much!

[tiff.t.txt](https://github.com/PhilterPaper/Perl-PDF-Builder/files/5427000/tiff.t.txt)

**Comment by carygravel** [comment]
If I remove Graphics::TIFF, the G3 test (10) fails with

`Chunked CCITT G4 TIFF not supported. at lib/PDF/Builder/Resource/XObject/Image/TIFF.pm line 238.`

The same happens if I also remove `convert`. So obviously I'm going to have to improve the skip. I'll work on it and let you know.

**Comment by carygravel** [comment]
[Here is a new pull request](https://github.com/PhilterPaper/Perl-PDF-Builder/pull/129).

**Pull request merged**
